-- Step 1: Create Roles and Users
CREATE ROLE FULL_ACCESS_ROLE;
CREATE ROLE LIMITED_ACCESS_ROLE;

GRANT USAGE ON ACCOUNT TO ROLE FULL_ACCESS_ROLE, ROLE LIMITED_ACCESS_ROLE;

CREATE USER admin_user PASSWORD='Admin@123' DEFAULT_ROLE=FULL_ACCESS_ROLE;
CREATE USER analyst_user PASSWORD='Analyst@123' DEFAULT_ROLE=LIMITED_ACCESS_ROLE;

GRANT ROLE FULL_ACCESS_ROLE TO USER admin_user;
GRANT ROLE LIMITED_ACCESS_ROLE TO USER analyst_user;