-- Step 2: Create Database and Schema
CREATE OR REPLACE DATABASE EMP_DB;
CREATE OR REPLACE SCHEMA HR_SCHEMA;
GRANT USAGE ON DATABASE EMP_DB TO ROLE FULL_ACCESS_ROLE;
GRANT USAGE ON DATABASE EMP_DB TO ROLE LIMITED_ACCESS_ROLE;
GRANT USAGE ON SCHEMA EMP_DB.HR_SCHEMA TO ROLE FULL_ACCESS_ROLE;
GRANT USAGE ON SCHEMA EMP_DB.HR_SCHEMA TO ROLE LIMITED_ACCESS_ROLE;