-- Step 4: Create Masking Policies
CREATE OR REPLACE MASKING POLICY EMAIL_MASK 
AS (val STRING) 
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('FULL_ACCESS_ROLE') THEN val
    ELSE CONCAT('XXXXXX@', SPLIT_PART(val, '@', 2))
END;

CREATE OR REPLACE MASKING POLICY SALARY_MASK 
AS (val NUMBER) 
RETURNS NUMBER ->
CASE
    WHEN CURRENT_ROLE() IN ('FULL_ACCESS_ROLE') THEN val
    ELSE NULL
END;